import { EventEmitter } from "node:events";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createInterface } from "node:readline";
import { promises as fs } from "node:fs";
import path from "node:path";
export interface RpcEnvelope { id?: number | string; method?: string; params?: unknown; result?: unknown; error?: { message?: string }; }
type Pending = { resolve: (value: unknown) => void; reject: (error: Error) => void; timer: NodeJS.Timeout };
export class CodexClient extends EventEmitter {
  private child: ChildProcessWithoutNullStreams | null = null; private nextId = 1; private pending = new Map<number, Pending>(); private starting: Promise<void> | null = null;
  constructor(private readonly root: string, private readonly entryOverride = process.env.TRAVEL_PLANNER_CODEX_ENTRY) { super(); }
  get running() { return Boolean(this.child && !this.child.killed); }
  async start() { if (this.starting) return this.starting; this.starting = this.startInternal().catch((error) => { this.starting = null; throw error; }); return this.starting; }
  private async startInternal() { const entry = this.entryOverride || path.join(this.root, "node_modules", "@openai", "codex", "bin", "codex.js"); await fs.access(entry); const env = { ...process.env }; delete env.OPENAI_API_KEY; delete env.OPENAI_ORG_ID; delete env.OPENAI_PROJECT_ID; const child = spawn(process.execPath, [entry, "app-server"], { cwd: this.root, env, stdio: ["pipe", "pipe", "pipe"], windowsHide: true }); this.child = child; child.on("exit", (code) => { const error = new Error(`Codex app-server 已退出（${code ?? "unknown"}）。`); for (const item of this.pending.values()) { clearTimeout(item.timer); item.reject(error); } this.pending.clear(); if (this.child === child) { this.child = null; this.starting = null; } this.emit("status", { running: false, error: error.message }); }); child.stderr.on("data", (chunk: Buffer) => { const message = chunk.toString("utf8").trim(); if (message) this.emit("diagnostic", { message }); }); createInterface({ input: child.stdout }).on("line", (line) => this.handleLine(line)); await this.call("initialize", { clientInfo: { name: "ai-travel-planner", title: "AI Travel Planner", version: "0.1.0" }, capabilities: { experimentalApi: true, requestAttestation: false } }); this.notify("initialized"); this.emit("status", { running: true }); }
  private handleLine(line: string) { let message: RpcEnvelope; try { message = JSON.parse(line); } catch { this.emit("diagnostic", { message: "Codex 返回了无法解析的消息。" }); return; } if (message.id !== undefined && (message.result !== undefined || message.error)) { const item = this.pending.get(Number(message.id)); if (!item) return; clearTimeout(item.timer); this.pending.delete(Number(message.id)); message.error ? item.reject(new Error(message.error.message || "Codex 请求失败。")) : item.resolve(message.result); return; } if (message.id !== undefined && message.method) { this.emit("serverRequest", message); return; } if (message.method) this.emit("notification", message); }
  private send(message: RpcEnvelope) { if (!this.child?.stdin.writable) throw new Error("Codex app-server 尚未运行。"); this.child.stdin.write(`${JSON.stringify(message)}\n`); }
  async call(method: string, params?: unknown, timeoutMs = 60000): Promise<any> { if (!this.child && method !== "initialize") await this.start(); const id = this.nextId++; const value = new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`${method} 请求超时。`)); }, timeoutMs); this.pending.set(id, { resolve, reject, timer }); }); this.send({ id, method, ...(params === undefined ? {} : { params }) }); return value; }
  notify(method: string, params?: unknown) { this.send({ method, ...(params === undefined ? {} : { params }) }); }
  respond(id: number | string, result: unknown) { this.send({ id, result }); }
  async stop() { const child = this.child; if (!child) return; this.child = null; this.starting = null; await new Promise<void>((resolve) => { const timer = setTimeout(resolve, 2000); child.once("exit", () => { clearTimeout(timer); resolve(); }); child.kill(); }); }
}
