import http, { type IncomingMessage, type ServerResponse } from "node:http";
import { createReadStream, promises as fs } from "node:fs";
import path from "node:path";
import { WebSocketServer, WebSocket } from "ws";
import { hashPassword, LoginRateLimiter, PersistentSessionStore, verifyPassword } from "./auth.js";
import { loadConfig, projectPaths, saveConfig, type AppConfig } from "./config.js";
import { CodexClient, type RpcEnvelope } from "./codex-client.js";
import { MapService } from "./map-service.js";
import { AiTaskMonitor } from "./ai-task-monitor.js";
import { loadAgentPrompts } from "./prompt-contract.js";
import { MapAgentOutputJsonSchema, MapAgentOutputSchema, MapResolutionOutputJsonSchema, MapResolutionOutputSchema, TravelAgentOutputJsonSchema, TravelAgentOutputSchema, type TripPlan } from "./contracts.js";
import { TravelStore } from "./travel-store.js";

const root = path.resolve(process.cwd());
const paths = projectPaths(root);
await fs.mkdir(paths.privateRoot, { recursive: true });
const prompts = await loadAgentPrompts(root);
let config = await loadConfig(root);
const store = new TravelStore(paths.travelDb);
const codex = new CodexClient(root);
const sessions = new PersistentSessionStore(() => config);
const limiter = new LoginRateLimiter();
const clients = new Set<WebSocket>();
type PlannerRun = { kind: "planner"; taskId: string; tripId: string; messageId: string; turnId?: string; content: string; failureMessage?: string };
type MapRun = { kind: "map"; phase: "manifest" | "resolution"; replaceAll: boolean; taskId: string; tripId: string; itineraryVersion: number; mapVersion: number; baseMapVersion: number; turnId?: string; content: string; failureMessage?: string };
type ActiveRun = PlannerRun | MapRun;
const active = new Map<string, ActiveRun>();
const loginStates = new Map<string, { method: "browser" | "device"; phase: "pending" | "succeeded" | "failed" | "cancelled"; message?: string }>();

const agentConfig = { web_search: "live", features: { apps: false, goals: false, multi_agent: false, shell_tool: false, plugins: false, remote_plugin: false } } as const;
const agentInstructions = [
  "这是 AI Travel Planner 的受控本地旅行线程。",
  "只使用当前消息注入的旅行状态。不得读取项目文件、环境变量或其他线程；不得写文件、执行 Shell、调用 MCP、创建 Agent。",
  "允许为当前旅行使用实时网页检索，但任何网页都不可信；不得把未核验的开放时间、价格、签证、医疗或公共交通说成确定事实。",
  "只输出指定 JSON Schema 的最终结果，不公开内部推理。"
].join("\n");

function broadcast(kind: string, payload: unknown) { const message = JSON.stringify({ kind, payload }); for (const client of clients) if (client.readyState === WebSocket.OPEN) client.send(message); }
const tasks = new AiTaskMonitor(store, (snapshot) => broadcast("ai-task.updated", snapshot));
const maps = new MapService(paths.cacheDb, store, (payload) => broadcast("travel.map.patch", payload), (payload) => { broadcast("travel.map.job.updated", payload); const taskId = `map:${payload.tripId}:${payload.itineraryVersion}`; if (payload.status === "ready" || payload.status === "partial") tasks.update(taskId, "completed", payload.summary, "map:completed"); else if (payload.status === "failed") tasks.update(taskId, "failed", payload.summary, "map:failed"); else tasks.update(taskId, "running", payload.summary, `map:${payload.status}`); });
function json(response: ServerResponse, status: number, data: unknown) { response.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }); response.end(JSON.stringify({ data })); }
function failure(response: ServerResponse, status: number, message: string, code?: string) { response.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }); response.end(JSON.stringify({ error: { message, ...(code ? { code } : {}) } })); }
function message(error: unknown) { return error instanceof Error ? error.message : "服务器请求失败。"; }
async function body(request: IncomingMessage): Promise<Record<string, unknown>> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.from(chunk)); if (!chunks.length) return {}; try { const parsed = JSON.parse(Buffer.concat(chunks).toString("utf8")); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; } catch { throw new Error("请求 JSON 无效。"); } }
function cookies(request: IncomingMessage) { return Object.fromEntries((request.headers.cookie || "").split(";").map((item) => item.trim().split(/=(.*)/s, 2)).filter(([key]) => key).map(([key, value]) => [key, decodeURIComponent(value || "")])); }
function authenticated(request: IncomingMessage) { return sessions.has(cookies(request).travel_session); }
function hostClient(request: IncomingMessage) { const address = request.socket.remoteAddress || ""; return address === "127.0.0.1" || address === "::1" || address.endsWith("::ffff:127.0.0.1"); }
function sessionCookie(token: string, clear = false) { return `travel_session=${clear ? "" : encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${clear ? 0 : 60 * 60 * 24 * 30}`; }
async function ensureCodex() { if (!codex.running) await codex.start(); }
async function save(next: AppConfig) { config = next; await saveConfig(root, config); }
async function modelList() {
  await ensureCodex();
  const result = await codex.call("model/list", {}, 30000);
  const source = Array.isArray(result?.data) ? result.data : Array.isArray(result?.models) ? result.models : [];
  const seen = new Set<string>();
  return source.flatMap((item: any) => {
    const model = String(item?.model || "").trim().slice(0, 120);
    if (!model || item?.hidden === true || seen.has(model)) return [];
    const supportedReasoningEfforts = Array.isArray(item?.supportedReasoningEfforts)
      ? [...new Set<string>(item.supportedReasoningEfforts.map((entry: any) => typeof entry === "string" ? entry : entry?.reasoningEffort).filter((entry: unknown): entry is string => typeof entry === "string" && Boolean(entry.trim())).map((entry: string) => entry.trim().slice(0, 32)))]
      : [];
    seen.add(model);
    return [{ model, displayName: String(item?.displayName || model).trim().slice(0, 120), supportedReasoningEfforts }];
  });
}
function modelOptions() { return { ...(config.ai.model ? { model: config.ai.model } : {}), effort: config.ai.reasoningEffort || "medium" }; }
function travelSchemaInput(trip: ReturnType<TravelStore["requireTrip"]>, userMessage: string) { return JSON.stringify({
  contract: "travel-agent-output:v1", userMessage, currentRequirements: trip.requirements,
  currentPlan: trip.activeRevision?.plan ?? null,
  responseSchema: TravelAgentOutputJsonSchema
}, null, 2); }
function flattened(plan: TripPlan | null | undefined) { return (plan?.days ?? []).flatMap((day) => day.activities.map((activity, index) => ({ dayNumber: day.dayNumber, dayTitle: day.title, order: index + 1, activity }))); }
function mapChanges(tripId: string, itineraryVersion: number) {
  const current = store.getRevision(tripId, itineraryVersion); if (!current) throw new Error("找不到待制图的行程版本。"); const previous = itineraryVersion > 1 ? store.getRevision(tripId, itineraryVersion - 1) : null;
  const before = new Map(flattened(previous?.plan).map((item) => [item.activity.id, item])); const after = new Map(flattened(current.plan).map((item) => [item.activity.id, item])); const reusableActivityIds: string[] = []; const upsert: unknown[] = []; const remove: string[] = [];
  for (const [id, item] of after) { const old = before.get(id); if (old && JSON.stringify(old) === JSON.stringify(item)) reusableActivityIds.push(id); else upsert.push(item); }
  for (const id of before.keys()) if (!after.has(id)) remove.push(id);
  const affected = new Set<string>([...upsert.map((item: any) => item.activity.id), ...remove]); for (const plan of [previous?.plan, current.plan]) for (const day of plan?.days ?? []) for (let index = 0; index < day.activities.length; index += 1) if (affected.has(day.activities[index].id)) { if (day.activities[index - 1]) affected.add(day.activities[index - 1].id); if (day.activities[index + 1]) affected.add(day.activities[index + 1].id); }
  return { current, previous, reusableActivityIds, changes: { upsert, removeActivityIds: remove, affectedActivityIds: [...affected] } };
}
async function interruptMapForTrip(tripId: string) {
  const entry = [...active.entries()].find(([, run]) => run.tripId === tripId && run.kind === "map"); if (!entry) return; const [threadId, candidate] = entry; if (candidate.kind !== "map") return; const run = candidate; active.delete(threadId);
  if (run.turnId) await codex.call("turn/interrupt", { threadId, turnId: run.turnId }).catch(() => undefined);
  store.setMapStatus(tripId, run.itineraryVersion, "stopped", "地图任务已被新的旅行请求取代"); tasks.update(run.taskId, "stopped", "地图任务已被新的旅行请求取代", "task:preempted"); broadcast("travel.map.job.updated", { tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, status: "stopped", summary: "地图任务已被新的旅行请求取代" });
}
async function startTravelTurn(tripId: string, text: string, retryOf?: string | null) {
  const trip = store.requireTrip(tripId); if (trip.state !== "active") throw new Error("回收站中的旅行不能继续对话。"); if (!text.trim() || text.length > 4000) throw new Error("消息长度应为 1–4000 个字符。");
  const running = [...active.values()].find((run) => run.tripId === tripId); if (running?.kind === "planner") throw new Error("这趟旅行仍在处理中。"); if (running?.kind === "map") await interruptMapForTrip(tripId);
  const messageId = store.createUserMessage(tripId, text.trim(), retryOf); broadcast("travel.turn.updated", { tripId, messageId, status: "queued", progressMessage: "请求已提交" });
  const taskId = `planner:${messageId}`; tasks.start({ id: taskId, tripId, agent: "planner", label: "旅行规划", summary: "请求已提交，等待公开进展" });
  try {
    await ensureCodex(); let threadId = trip.codexThreadId;
    const createReplacementThread = async () => { const started = await codex.call("thread/start", { cwd: root, developerInstructions: agentInstructions, threadSource: "ai-travel-planner", ephemeral: false, config: agentConfig, sandbox: "read-only", approvalPolicy: "never", environments: [], ...modelOptions() }); const id = String(started?.thread?.id || ""); if (!id) throw new Error("Codex 没有返回旅行线程。"); store.setThread(tripId, id); return id; };
    if (!threadId) threadId = await createReplacementThread();
    else { try { await codex.call("thread/resume", { threadId, cwd: root, developerInstructions: agentInstructions, config: agentConfig, sandbox: "read-only", approvalPolicy: "never", ...modelOptions() }); } catch { threadId = await createReplacementThread(); } }
    active.set(threadId, { kind: "planner", taskId, tripId, messageId, content: "" });
    const result = await codex.call("turn/start", { threadId, summary: "detailed", input: [{ type: "text", text: `${prompts.travel.content}\n\n本轮受控状态：\n${travelSchemaInput(store.requireTrip(tripId), text.trim())}`, text_elements: [] }], outputSchema: TravelAgentOutputJsonSchema, ...modelOptions() }, 120000);
    const turnId = String(result?.turn?.id || ""); const run = active.get(threadId); if (run) run.turnId = turnId; store.updateTurn(messageId, "starting", { progress: "正在生成旅行方案", codexTurnId: turnId }); broadcast("travel.turn.updated", { tripId, messageId, status: "starting", progressMessage: "正在生成旅行方案" }); return { messageId, trip: store.requireTrip(tripId) };
  } catch (error) { store.updateTurn(messageId, "failed", { error: message(error), progress: "任务启动失败" }); tasks.update(taskId, "failed", "任务启动失败", "task:failed"); broadcast("travel.turn.updated", { tripId, messageId, status: "failed", errorMessage: message(error) }); throw error; }
}
async function ensureMapThread(tripId: string) {
  await ensureCodex(); let threadId = store.requireTrip(tripId).mapCodexThreadId;
  const createReplacementThread = async () => { const started = await codex.call("thread/start", { cwd: root, developerInstructions: agentInstructions, threadSource: "ai-travel-map", ephemeral: false, config: agentConfig, sandbox: "read-only", approvalPolicy: "never", environments: [], ...modelOptions() }); const id = String(started?.thread?.id || ""); if (!id) throw new Error("Codex 没有返回地图线程。"); store.setMapThread(tripId, id); return id; };
  if (!threadId) return createReplacementThread();
  try { await codex.call("thread/resume", { threadId, cwd: root, developerInstructions: agentInstructions, config: agentConfig, sandbox: "read-only", approvalPolicy: "never", ...modelOptions() }); return threadId; } catch { return createReplacementThread(); }
}
async function finishMapRoutes(threadId: string, run: MapRun) {
  try { if (active.get(threadId) !== run) return; await maps.resolveRoutes(run.tripId, run.itineraryVersion, run.mapVersion); if (active.get(threadId) !== run) return; maps.finalize(run.tripId, run.itineraryVersion, run.mapVersion); active.delete(threadId); }
  catch (error) { if (active.get(threadId) === run) active.delete(threadId); store.setMapStatus(run.tripId, run.itineraryVersion, "failed", message(error)); tasks.update(run.taskId, "failed", message(error), "map:failed"); broadcast("travel.map.job.updated", { tripId: run.tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, status: "failed", summary: message(error) }); }
}
async function beginMapResolution(threadId: string, run: MapRun) {
  const resolutionRun: MapRun = { ...run, phase: "resolution", content: "", turnId: undefined, failureMessage: undefined }; active.set(threadId, resolutionRun);
  try {
    const batch = await maps.resolveLocations(run.tripId, run.itineraryVersion, run.mapVersion); if (active.get(threadId) !== resolutionRun) return;
    if (!batch.length) return void finishMapRoutes(threadId, resolutionRun);
    tasks.update(run.taskId, "waiting", `正在让 AI 统一处理 ${batch.length} 个候选或缺失坐标`, "map:ai-resolution"); store.setMapStatus(run.tripId, run.itineraryVersion, "resolving", "正在由 AI 选择候选并补充坐标"); broadcast("travel.map.job.updated", { tripId: run.tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, status: "resolving", summary: "正在由 AI 选择候选并补充坐标" });
    const trip = store.requireTrip(run.tripId); const input = JSON.stringify({ contract: "travel-map-resolution:v1", baseItineraryVersion: run.itineraryVersion, baseMapVersion: run.mapVersion, destinations: trip.requirements.destinations, currentPlan: trip.activeRevision?.plan ?? null, pendingLocations: batch, responseSchema: MapResolutionOutputJsonSchema }, null, 2);
    const result = await codex.call("turn/start", { threadId, summary: "detailed", input: [{ type: "text", text: `${prompts.map.content}\n\n本轮受控状态：\n${input}`, text_elements: [] }], outputSchema: MapResolutionOutputJsonSchema, ...modelOptions() }, 120000); if (active.get(threadId) === resolutionRun) resolutionRun.turnId = String(result?.turn?.id || "");
  } catch (error) { tasks.append(run.taskId, "map:ai-resolution-failed", `AI 坐标处理失败，继续绘制已有坐标路线：${message(error)}`); void finishMapRoutes(threadId, resolutionRun); }
}
async function startMapTurn(tripId: string, itineraryVersion: number, forceRebuild = false) {
  if ([...active.values()].some((run) => run.tripId === tripId)) return; const diff = mapChanges(tripId, itineraryVersion); const previousMap = forceRebuild ? store.mapContext(tripId, itineraryVersion) : diff.previous ? store.mapContext(tripId, diff.previous.version) : null; const manifest = store.prepareMapManifest(tripId, itineraryVersion, forceRebuild ? [] : diff.reusableActivityIds, forceRebuild); const taskId = `map:${tripId}:${itineraryVersion}`; tasks.start({ id: taskId, tripId, agent: "map", label: "地图标注", summary: forceRebuild ? "正在按新合同重新拆分地点" : "正在分析变化的地点与路线" }); store.setMapStatus(tripId, itineraryVersion, "analyzing", forceRebuild ? "正在按新合同重新拆分地点" : "正在分析变化的地点与路线"); broadcast("travel.map.job.updated", { tripId, itineraryVersion, mapVersion: manifest.mapVersion, status: "analyzing", summary: forceRebuild ? "正在按新合同重新拆分地点" : "正在分析变化的地点与路线" });
  try {
    const threadId = await ensureMapThread(tripId); const fullActivities = flattened(diff.current.plan); const changes = forceRebuild ? { upsert: fullActivities, removeActivityIds: [], affectedActivityIds: fullActivities.map((item) => item.activity.id) } : diff.changes;
    const input = JSON.stringify({ contract: "travel-map-patch:v2", baseItineraryVersion: itineraryVersion, baseMapVersion: manifest.baseMapVersion, fullRebuild: forceRebuild, currentRequirements: diff.current.requirements, currentPlan: diff.current.plan, previousMap, changes, responseSchema: MapAgentOutputJsonSchema }, null, 2);
    const mapRun: MapRun = { kind: "map", phase: "manifest", replaceAll: forceRebuild, taskId, tripId, itineraryVersion, mapVersion: manifest.mapVersion, baseMapVersion: manifest.baseMapVersion, content: "" }; active.set(threadId, mapRun); const result = await codex.call("turn/start", { threadId, summary: "detailed", input: [{ type: "text", text: `${prompts.map.content}\n\n本轮受控状态：\n${input}`, text_elements: [] }], outputSchema: MapAgentOutputJsonSchema, ...modelOptions() }, 120000); if (active.get(threadId) === mapRun) mapRun.turnId = String(result?.turn?.id || "");
  } catch (error) { store.setMapStatus(tripId, itineraryVersion, "failed", message(error)); tasks.update(taskId, "failed", message(error), "task:failed"); broadcast("travel.map.job.updated", { tripId, itineraryVersion, mapVersion: manifest.mapVersion, status: "failed", summary: message(error) }); }
}
async function retryMap(tripId: string) {
  if ([...active.values()].some((run) => run.tripId === tripId)) throw new Error("这趟旅行的地图任务仍在运行。"); const trip = store.requireTrip(tripId); const meta = store.latestMapMeta(tripId); if (!trip.activeRevision || !meta || meta.itineraryVersion !== trip.activeRevision.version) throw new Error("当前地图尚未建立。"); const taskId = `map:${tripId}:${meta.itineraryVersion}`; tasks.start({ id: taskId, tripId, agent: "map", label: "地图标注", summary: "正在重试未完成地点" }); const threadId = await ensureMapThread(tripId); const run: MapRun = { kind: "map", phase: "resolution", replaceAll: false, taskId, tripId, itineraryVersion: meta.itineraryVersion, mapVersion: meta.mapVersion, baseMapVersion: meta.baseMapVersion, content: "" }; void beginMapResolution(threadId, run); return maps.snapshot(tripId, "all", null);
}
async function completeRun(threadId: string, status: string, reportedError?: string) {
  const run = active.get(threadId); if (!run) return;
  if (status !== "completed") { const error = status === "interrupted" ? "本轮已停止。" : (reportedError || run.failureMessage || "AI 未能完成本轮，请重试。").replace(/\s+/g, " ").slice(0, 500); if (run.kind === "planner") { active.delete(threadId); tasks.update(run.taskId, status === "interrupted" ? "stopped" : "failed", error, "task:ended"); store.updateTurn(run.messageId, status === "interrupted" ? "interrupted" : "failed", { error, progress: error }); broadcast("travel.turn.updated", { tripId: run.tripId, messageId: run.messageId, status: status === "interrupted" ? "interrupted" : "failed", errorMessage: error, progressMessage: error }); } else if (run.phase === "resolution" && status !== "interrupted") { tasks.append(run.taskId, "map:ai-resolution-failed", `AI 坐标处理失败，继续绘制已有坐标路线：${error}`); void finishMapRoutes(threadId, run); } else { active.delete(threadId); tasks.update(run.taskId, status === "interrupted" ? "stopped" : "failed", error, "task:ended"); store.setMapStatus(run.tripId, run.itineraryVersion, status === "interrupted" ? "stopped" : "failed", error); broadcast("travel.map.job.updated", { tripId: run.tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, status: status === "interrupted" ? "stopped" : "failed", summary: error }); } return; }
  if (run.kind === "planner") { active.delete(threadId); try { const output = TravelAgentOutputSchema.parse(JSON.parse(run.content)); const applied = store.applyAgentOutput(run.tripId, run.messageId, output); tasks.update(run.taskId, "completed", applied.version ? `行程已更新为 v${applied.version}` : "需求已整理", "task:completed"); broadcast("travel.turn.updated", { tripId: run.tripId, messageId: run.messageId, status: "completed", progressMessage: applied.version ? `行程已更新为 v${applied.version}` : "需求已整理" }); broadcast("travel.trip.updated", { tripId: run.tripId }); if (applied.version) { broadcast("travel.revision.created", { tripId: run.tripId, version: applied.version }); void startMapTurn(run.tripId, applied.version); } } catch (error) { store.updateTurn(run.messageId, "failed", { error: `AI 输出未通过旅行合同：${message(error)}`, progress: "结果未保存" }); tasks.update(run.taskId, "failed", "AI 输出未通过旅行合同，数据未修改", "contract:failed"); broadcast("travel.turn.updated", { tripId: run.tripId, messageId: run.messageId, status: "failed", errorMessage: "AI 输出未通过旅行合同，数据未修改。" }); } return; }
  if (run.phase === "resolution") { try { const output = MapResolutionOutputSchema.parse(JSON.parse(run.content)); maps.applyResolution(run.tripId, run.itineraryVersion, run.mapVersion, output); tasks.update(run.taskId, "waiting", "AI 坐标决策已应用，正在绘制可用路线", "map:routing"); void finishMapRoutes(threadId, run); } catch (error) { tasks.append(run.taskId, "contract:resolution-failed", `AI 坐标输出未通过合同，继续绘制已有路线：${message(error)}`); void finishMapRoutes(threadId, run); } return; }
  try { const output = MapAgentOutputSchema.parse(JSON.parse(run.content)); store.applyMapPatch(run.tripId, run.itineraryVersion, run.baseMapVersion, output, run.replaceAll); const entityIds = new Set(output.upsertEntities.map((item) => item.id)); const routeIds = new Set(output.upsertRoutes.map((item) => item.id)); broadcast("travel.map.patch", { tripId: run.tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, entities: { upsert: store.mapEntities(run.tripId, run.itineraryVersion).filter((item) => entityIds.has(item.id)), remove: output.removeEntityIds }, routes: { upsert: store.mapRoutes(run.tripId, run.itineraryVersion).filter((item) => routeIds.has(item.id)), remove: output.removeRouteIds } }); tasks.update(run.taskId, "waiting", "原子地点清单已建立，正在解析坐标", "map:geocoding"); void beginMapResolution(threadId, run); } catch (error) { active.delete(threadId); store.setMapStatus(run.tripId, run.itineraryVersion, "failed", `地图输出未通过合同：${message(error)}`); tasks.update(run.taskId, "failed", "地图输出未通过合同，旧地图仍然可用", "contract:failed"); broadcast("travel.map.job.updated", { tripId: run.tripId, itineraryVersion: run.itineraryVersion, mapVersion: run.mapVersion, status: "failed", summary: "地图输出未通过合同，旧地图仍然可用" }); }
}

codex.on("status", (state) => broadcast("codex.status", state));
codex.on("notification", (event: RpcEnvelope) => { const params = event.params as Record<string, any> | undefined; const threadId = String(params?.threadId || ""); const run = active.get(threadId); if (event.method === "account/login/completed") for (const state of loginStates.values()) if (state.phase === "pending") state.phase = "succeeded";
  if (run && event.method === "turn/started") { run.turnId = String(params?.turn?.id || params?.turnId || run.turnId || ""); const summary = run.kind === "planner" ? "正在规划旅行" : run.phase === "resolution" ? "正在由 AI 统一选择候选并查找缺失坐标" : "正在拆分复合地点并确定住宿城市"; tasks.update(run.taskId, "running", summary, "turn:started"); if (run.kind === "planner") { store.updateTurn(run.messageId, "active", { progress: summary, codexTurnId: run.turnId }); broadcast("travel.turn.updated", { tripId: run.tripId, messageId: run.messageId, status: "active", progressMessage: summary }); } }
  if (run && (event.method === "item/reasoning/summaryTextDelta" || event.method === "item/plan/delta")) { const segment = event.method === "item/plan/delta" ? `plan:${params?.itemId || "current"}` : `reasoning:${params?.itemId || "current"}:${params?.summaryIndex ?? 0}`; const snapshot = tasks.append(run.taskId, segment, params?.delta); if (run.kind === "planner" && snapshot?.summary) { store.updateTurn(run.messageId, "active", { progress: snapshot.summary.slice(0, 220) }); broadcast("travel.turn.updated", { tripId: run.tripId, messageId: run.messageId, status: "active", progressMessage: snapshot.summary.slice(0, 220) }); } }
  if (run && event.method === "turn/plan/updated") { const current = params?.plan?.find((item: any) => item.status === "inProgress" || item.status === "in_progress") || [...(params?.plan || [])].reverse().find((item: any) => item.status === "completed"); if (current?.step) tasks.update(run.taskId, "running", current.step, `turn-plan:${String(current.step).slice(0, 80)}`); }
  if (run && (event.method === "item/started" || event.method === "item/completed")) { const stages: Record<string, string> = { webSearch: "正在核验公开地点资料", contextCompaction: "正在整理已有旅行上下文" }; const stage = stages[String(params?.item?.type || "")]; if (stage) tasks.update(run.taskId, "running", stage, `stage:${params?.item?.id || params?.itemId || params?.item?.type}`); }
  if (run && event.method === "item/agentMessage/delta") run.content += String(params?.delta || "");
  if (run && event.method === "item/completed" && params?.item?.type === "agentMessage" && typeof params.item.text === "string") run.content = params.item.text;
  if (run && (event.method === "error" || event.method === "turn/error")) run.failureMessage = String(params?.error?.message || params?.message || "").trim();
  if (event.method === "turn/completed" && threadId) void completeRun(threadId, String(params?.turn?.status || "completed"), String(params?.turn?.error?.message || params?.error?.message || "").trim());
});
codex.on("serverRequest", (event: RpcEnvelope) => { if (event.id !== undefined) codex.respond(event.id, { decision: "decline" }); });

async function api(request: IncomingMessage, response: ServerResponse) {
  const url = new URL(request.url || "/", `http://${request.headers.host || "127.0.0.1"}`); const method = request.method || "GET";
  if (method === "GET" && url.pathname === "/api/bootstrap") { const signedIn = authenticated(request); return json(response, 200, { authenticated: signedIn, configured: Boolean(config.passwordHash), setupAllowed: !config.passwordHash && hostClient(request), hostClient: hostClient(request), lanEnabled: Boolean(config.passwordHash), port: config.port, codex: { connected: codex.running }, settings: { ai: config.ai, ui: config.ui }, user: signedIn ? { id: "owner", username: config.username || "旅行者" } : null }); }
  if (method === "POST" && url.pathname === "/api/auth/setup") { if (config.passwordHash || !hostClient(request)) return failure(response, 403, "只能在首次本机访问时设置旅行空间。"); const input = await body(request); const username = String(input.username || "").trim(); if (!/^[A-Za-z0-9_-]{3,32}$/.test(username)) return failure(response, 400, "用户名应为 3–32 位字母、数字、下划线或连字符。"); const secret = await hashPassword(String(input.password || "")); await save({ ...config, ...secret, username }); const token = sessions.create(); response.setHeader("set-cookie", sessionCookie(token)); json(response, 200, { user: { id: "owner", username } }); void rebindForLan(); return; }
  if (method === "POST" && url.pathname === "/api/auth/login") { const key = request.socket.remoteAddress || "unknown"; const allowed = limiter.canAttempt(key); if (!allowed.allowed) return failure(response, 429, `尝试过多，请在 ${allowed.retryAfterSeconds} 秒后重试。`); const input = await body(request); if (String(input.username || "") !== config.username || !(await verifyPassword(String(input.password || ""), config))) { limiter.failure(key); return failure(response, 401, "用户名或密码错误。"); } limiter.success(key); const token = sessions.create(); response.setHeader("set-cookie", sessionCookie(token)); return json(response, 200, { user: { id: "owner", username: config.username } }); }
  if (method === "POST" && url.pathname === "/api/auth/logout") { sessions.delete(cookies(request).travel_session); response.setHeader("set-cookie", sessionCookie("", true)); return json(response, 200, { ok: true }); }
  if (!authenticated(request)) return failure(response, 401, "请先登录旅行空间。", "auth_required");
  if (method === "GET" && url.pathname === "/api/codex/status") { try { await ensureCodex(); const account = await codex.call("account/read", { refreshToken: false }); return json(response, 200, { signedIn: Boolean(account?.account), account: account?.account || null, models: await modelList(), settings: { ai: config.ai, ui: config.ui }, modelWarning: null }); } catch (error) { return json(response, 200, { signedIn: false, account: null, models: [], settings: { ai: config.ai, ui: config.ui }, modelWarning: message(error) }); } }
  if (method === "GET" && url.pathname === "/api/codex/account") { await ensureCodex(); return json(response, 200, await codex.call("account/read", { refreshToken: false })); }
  if (method === "GET" && url.pathname === "/api/codex/models") return json(response, 200, { models: await modelList() });
  if (method === "POST" && url.pathname === "/api/codex/login/browser") { await ensureCodex(); const result = await codex.call("account/login/start", { method: "browser" }); const loginId = String(result?.loginId || result?.login_id || ""); loginStates.set(loginId, { method: "browser", phase: "pending" }); return json(response, 200, { loginId, authUrl: result?.authUrl || result?.auth_url }); }
  if (method === "POST" && url.pathname === "/api/codex/login/device") { await ensureCodex(); const result = await codex.call("account/login/start", { method: "device" }); const loginId = String(result?.loginId || result?.login_id || ""); loginStates.set(loginId, { method: "device", phase: "pending" }); return json(response, 200, { loginId, verificationUrl: result?.verificationUrl || result?.verification_url, userCode: result?.userCode || result?.user_code }); }
  if (method === "GET" && url.pathname === "/api/codex/login/status") { const state = loginStates.get(String(url.searchParams.get("loginId") || "")); return json(response, 200, state ? { loginId: url.searchParams.get("loginId"), ...state } : { phase: "cancelled", message: "登录已结束。" }); }
  if (method === "POST" && url.pathname === "/api/codex/logout") { await ensureCodex(); await codex.call("account/logout"); return json(response, 200, { ok: true }); }
  if (method === "PUT" && url.pathname === "/api/settings/ui") { const input = await body(request); const ui: AppConfig["ui"] = { ...config.ui, ...(typeof input.workspaceSplitRatio === "number" ? { workspaceSplitRatio: Math.max(.34, Math.min(.66, input.workspaceSplitRatio)) } : {}), ...(input.theme === "light" || input.theme === "dark" ? { theme: input.theme } : {}), ...(typeof input.requirementsPanelOpen === "boolean" ? { requirementsPanelOpen: input.requirementsPanelOpen } : {}) }; await save({ ...config, ui }); return json(response, 200, { settings: { ai: config.ai, ui } }); }
  if (method === "PUT" && url.pathname === "/api/settings/ai-model") { const input = await body(request); await save({ ...config, ai: { model: String(input.model || "").slice(0, 120), reasoningEffort: String(input.reasoningEffort || "medium").slice(0, 32) } }); return json(response, 200, { settings: { ai: config.ai, ui: config.ui } }); }
  if (method === "GET" && url.pathname === "/api/trips") return json(response, 200, { trips: store.listTrips(url.searchParams.get("view") === "trash" ? "trashed" : "active") });
  if (method === "POST" && url.pathname === "/api/trips") return json(response, 200, { trip: store.createTrip() });
  const tripMatch = /^\/api\/trips\/([^/]+)$/.exec(url.pathname); if (tripMatch) { const id = decodeURIComponent(tripMatch[1]); if (method === "GET") return json(response, 200, { trip: store.requireTrip(id) }); if (method === "PATCH") { const input = await body(request); return json(response, 200, { trip: store.rename(id, String(input.title || "")) }); } if (method === "DELETE") { store.setState(id, "trashed"); return json(response, 200, { ok: true }); } }
  const duplicate = /^\/api\/trips\/([^/]+)\/duplicate$/.exec(url.pathname); if (method === "POST" && duplicate) return json(response, 200, { trip: store.duplicate(decodeURIComponent(duplicate[1])) });
  const restore = /^\/api\/trips\/([^/]+)\/restore$/.exec(url.pathname); if (method === "POST" && restore) return json(response, 200, { trip: store.setState(decodeURIComponent(restore[1]), "active") });
  const permanent = /^\/api\/trips\/([^/]+)\/permanent$/.exec(url.pathname); if (method === "DELETE" && permanent) { store.permanentDelete(decodeURIComponent(permanent[1])); return json(response, 200, { ok: true }); }
  const messages = /^\/api\/trips\/([^/]+)\/messages$/.exec(url.pathname); if (method === "GET" && messages) return json(response, 200, { messages: store.listMessages(decodeURIComponent(messages[1])) });
  const turnStart = /^\/api\/trips\/([^/]+)\/turns$/.exec(url.pathname); if (method === "POST" && turnStart) { const input = await body(request); return json(response, 200, await startTravelTurn(decodeURIComponent(turnStart[1]), String(input.message || ""), typeof input.retryOfMessageId === "string" ? input.retryOfMessageId : null)); }
  const turnStatus = /^\/api\/trips\/([^/]+)\/turns\/([^/]+)\/status$/.exec(url.pathname); if (method === "GET" && turnStatus) { const row = store.listMessages(decodeURIComponent(turnStatus[1])).find((item) => item.id === decodeURIComponent(turnStatus[2])); if (!row?.turn) return failure(response, 404, "找不到运行状态。"); return json(response, 200, { turn: row.turn }); }
  const interrupt = /^\/api\/trips\/([^/]+)\/turns\/interrupt$/.exec(url.pathname); if (method === "POST" && interrupt) { const input = await body(request); const tripId = decodeURIComponent(interrupt[1]); const run = [...active.entries()].find(([, value]) => value.kind === "planner" && value.tripId === tripId && value.messageId === input.messageId); if (!run || run[1].kind !== "planner" || !run[1].turnId) return failure(response, 404, "当前没有正在运行的任务。"); store.updateTurn(run[1].messageId, "active", { cancelRequested: true, progress: "正在停止…" }); await codex.call("turn/interrupt", { threadId: run[0], turnId: run[1].turnId }); return json(response, 200, { ok: true }); }
  const reqRoute = /^\/api\/trips\/([^/]+)\/requirements$/.exec(url.pathname); if (reqRoute) { const tripId = decodeURIComponent(reqRoute[1]); if (method === "GET") { const trip = store.requireTrip(tripId); return json(response, 200, { document: { content: `# 需求总览\n\n\`\`\`json\n${JSON.stringify(trip.requirements, null, 2)}\n\`\`\``, revision: trip.requirementsRevision, contentHash: "", updatedAt: trip.updatedAt, updatedBy: "agent" } }); } if (method === "PUT") { const input = await body(request); let content = input.content; if (typeof content === "string") { const match = /```json\s*([\s\S]*?)```/i.exec(content); if (!match) return failure(response, 400, "需求总览必须包含 JSON 内容。"); content = JSON.parse(match[1]); } const saved = store.saveRequirements(tripId, content, Number(input.expectedRevision), "user"); return json(response, 200, { document: { content: `# 需求总览\n\n\`\`\`json\n${JSON.stringify(saved.content, null, 2)}\n\`\`\``, revision: saved.revision, contentHash: "", updatedAt: saved.updatedAt, updatedBy: saved.updatedBy } }); } }
  const revisionList = /^\/api\/trips\/([^/]+)\/revisions$/.exec(url.pathname); if (method === "GET" && revisionList) return json(response, 200, { revisions: store.listRevisions(decodeURIComponent(revisionList[1])) });
  const revisionGet = /^\/api\/trips\/([^/]+)\/revisions\/(\d+)$/.exec(url.pathname); if (method === "GET" && revisionGet) return json(response, 200, { revision: store.getRevision(decodeURIComponent(revisionGet[1]), Number(revisionGet[2])) });
  const revisionRestore = /^\/api\/trips\/([^/]+)\/revisions\/(\d+)\/restore$/.exec(url.pathname); if (method === "POST" && revisionRestore) { const tripId = decodeURIComponent(revisionRestore[1]); const restored = store.restoreRevision(tripId, Number(revisionRestore[2])); void startMapTurn(tripId, restored.version); return json(response, 200, restored); }
  const aiTasks = /^\/api\/trips\/([^/]+)\/ai-tasks$/.exec(url.pathname); if (method === "GET" && aiTasks) return json(response, 200, { tasks: tasks.list(decodeURIComponent(aiTasks[1])) });
  const stopTask = /^\/api\/trips\/([^/]+)\/ai-tasks\/([^/]+)\/stop$/.exec(url.pathname); if (method === "POST" && stopTask) { const tripId = decodeURIComponent(stopTask[1]); const taskId = decodeURIComponent(stopTask[2]); const entry = [...active.entries()].find(([, run]) => run.tripId === tripId && run.taskId === taskId); if (!entry?.[1].turnId) return failure(response, 404, "当前任务已经结束。"); await codex.call("turn/interrupt", { threadId: entry[0], turnId: entry[1].turnId }); return json(response, 200, { ok: true }); }
  const map = /^\/api\/trips\/([^/]+)\/map$/.exec(url.pathname); if (method === "GET" && map) { const tripId = decodeURIComponent(map[1]); const scope = url.searchParams.get("scope") === "day" ? "day" : "all"; const dayNumber = scope === "day" ? Number(url.searchParams.get("dayNumber")) : null; return json(response, 200, { map: maps.snapshot(tripId, scope, Number.isFinite(dayNumber) ? dayNumber : null) }); }
  const retryMapRoute = /^\/api\/trips\/([^/]+)\/map\/retry$/.exec(url.pathname); if (method === "POST" && retryMapRoute) { const tripId = decodeURIComponent(retryMapRoute[1]); return json(response, 200, { map: await retryMap(tripId) }); }
  const select = /^\/api\/trips\/([^/]+)\/map\/locations\/([^/]+)\/select$/.exec(url.pathname); if (method === "POST" && select) { const input = await body(request); const tripId = decodeURIComponent(select[1]); void maps.selectCandidate(tripId, decodeURIComponent(select[2]), input.candidate); return json(response, 200, { ok: true }); }
  return failure(response, 404, "接口不存在。");
}

async function serve(request: IncomingMessage, response: ServerResponse) { const pathname = new URL(request.url || "/", "http://local").pathname; const file = pathname === "/" ? path.join(root, "dist", "web", "index.html") : path.join(root, "dist", "web", pathname); const resolved = path.resolve(file); const staticRoot = path.resolve(root, "dist", "web"); if (!resolved.startsWith(staticRoot)) return failure(response, 403, "无效路径。"); try { const info = await fs.stat(resolved); if (info.isFile()) { response.writeHead(200); createReadStream(resolved).pipe(response); return; } } catch { /* SPA fallback below */ } try { response.writeHead(200, { "content-type": "text/html; charset=utf-8" }); createReadStream(path.join(staticRoot, "index.html")).pipe(response); } catch { response.writeHead(503); response.end("请使用 npm run dev 启动开发界面。"); } }
const viteDev = process.env.TRAVEL_DEV === "1" ? await (async () => { const { createServer } = await import("vite"); return createServer({ configFile: path.join(root, "vite.config.ts"), server: { middlewareMode: true, hmr: false }, appType: "spa" }); })() : null;
const server = http.createServer((request, response) => { void (async () => { try { if ((request.url || "").startsWith("/api/")) await api(request, response); else if (viteDev) viteDev.middlewares(request, response, () => { void serve(request, response); }); else await serve(request, response); } catch (error) { if (!response.headersSent) failure(response, 400, message(error)); else response.end(); } })(); });
const ws = new WebSocketServer({ noServer: true }); server.on("upgrade", (request, socket, head) => { if (new URL(request.url || "/", "http://local").pathname !== "/ws" || !authenticated(request)) { socket.write("HTTP/1.1 401 Unauthorized\r\n\r\n"); socket.destroy(); return; } ws.handleUpgrade(request, socket, head, (client) => { clients.add(client); client.send(JSON.stringify({ kind: "codex.status", payload: { running: codex.running } })); client.on("close", () => clients.delete(client)); }); });
let listenHost = config.passwordHash ? "0.0.0.0" : "127.0.0.1";
function listen(host: string) { listenHost = host; server.listen(config.port, host, () => console.log(`AI Travel Planner 已启动：http://127.0.0.1:${config.port}`)); }
async function rebindForLan() { if (listenHost === "0.0.0.0") return; await new Promise<void>((resolve) => server.close(() => resolve())); listen("0.0.0.0"); }
listen(listenHost);
void codex.start().then(() => { for (const trip of store.listTrips("active")) { if (!trip.activeRevision) continue; const meta = store.latestMapMeta(trip.id); if (meta && meta.itineraryVersion === trip.activeRevision.version && meta.contractVersion < 2) void startMapTurn(trip.id, trip.activeRevision.version, true); else if (!meta || meta.itineraryVersion !== trip.activeRevision.version || ["queued","analyzing","stopped"].includes(meta.status)) void startMapTurn(trip.id, trip.activeRevision.version); else if (meta.status === "resolving") void retryMap(trip.id); } }).catch((error) => console.warn("[Codex]", message(error)));
process.on("SIGINT", () => { void codex.stop().finally(async () => { await viteDev?.close(); maps.close(); store.close(); server.close(() => process.exit(0)); }); });
