import { DatabaseSync } from "node:sqlite";
import type { Candidate, MapView, TripPlan } from "./contracts.js";
import type { TripDetail, TravelStore } from "./travel-store.js";

type CacheRow = { payload_json: string; expires_at: number };
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const candidate = (item: Record<string, unknown>): Candidate | null => {
  const lat = Number(item.lat); const lon = Number(item.lon); const id = String(item.place_id ?? ""); const name = String(item.display_name ?? "");
  return id && name && Number.isFinite(lat) && Number.isFinite(lon) ? { providerPlaceId: id, displayName: name, latitude: lat, longitude: lon, category: typeof item.category === "string" ? item.category : null, sourceUrl: `https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}` } : null;
};

export class MapService {
  private readonly db: DatabaseSync; private nextRequest = 0;
  constructor(filename: string, private readonly store: TravelStore) { this.db = new DatabaseSync(filename); this.db.exec("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS geocode_cache(key TEXT PRIMARY KEY,payload_json TEXT NOT NULL,expires_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS route_cache(key TEXT PRIMARY KEY,payload_json TEXT NOT NULL,expires_at INTEGER NOT NULL);"); }
  close() { this.db.close(); }
  private cached<T>(table: "geocode_cache" | "route_cache", key: string): T | null { const row = this.db.prepare(`SELECT payload_json,expires_at FROM ${table} WHERE key=?`).get(key) as CacheRow | undefined; if (!row || row.expires_at < Date.now()) return null; try { return JSON.parse(row.payload_json) as T; } catch { return null; } }
  private save<T>(table: "geocode_cache" | "route_cache", key: string, payload: T, ttlMs: number) { this.db.prepare(`INSERT INTO ${table}(key,payload_json,expires_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET payload_json=excluded.payload_json,expires_at=excluded.expires_at`).run(key, JSON.stringify(payload), Date.now() + ttlMs); }
  private async throttle() { const wait = Math.max(0, this.nextRequest - Date.now()); if (wait) await sleep(wait); this.nextRequest = Date.now() + 1100; }
  private async geocode(query: string): Promise<Candidate[]> { const key = query.trim().toLocaleLowerCase(); const cached = this.cached<Candidate[]>("geocode_cache", key); if (cached) return cached; await this.throttle(); const url = new URL("https://nominatim.openstreetmap.org/search"); url.searchParams.set("format", "jsonv2"); url.searchParams.set("limit", "5"); url.searchParams.set("q", query); const response = await fetch(url, { headers: { "User-Agent": "AI-Travel-Planner/0.1 (personal local travel planner)", Accept: "application/json" } }); if (!response.ok) throw new Error("公开地点服务暂时不可用。"); const data = await response.json() as unknown; const values = Array.isArray(data) ? data.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")).map(candidate).filter((item): item is Candidate => item !== null) : []; this.save("geocode_cache", key, values, 30 * 24 * 60 * 60 * 1000); return values; }
  private profile(mode: string) { if (mode === "bike") return "https://routing.openstreetmap.de/routed-bike/route/v1/driving"; if (mode === "walk") return "https://routing.openstreetmap.de/routed-foot/route/v1/driving"; return "https://routing.openstreetmap.de/routed-car/route/v1/driving"; }
  private async route(from: Candidate, to: Candidate, mode: string): Promise<{ geometry: unknown | null; warning: string | null }> { if (mode === "transit_advisory" || mode === "none") return { geometry: null, warning: mode === "transit_advisory" ? "公共交通仅作未实时核验建议。" : null }; const key = `${mode}:${from.longitude},${from.latitude}:${to.longitude},${to.latitude}`; const cached = this.cached<{ geometry: unknown | null; warning: string | null }>("route_cache", key); if (cached) return cached; await this.throttle(); const url = new URL(`${this.profile(mode)}/${from.longitude},${from.latitude};${to.longitude},${to.latitude}`); url.searchParams.set("overview", "full"); url.searchParams.set("geometries", "geojson"); const response = await fetch(url, { headers: { "User-Agent": "AI-Travel-Planner/0.1 (personal local travel planner)", Accept: "application/json" } }); if (!response.ok) return { geometry: null, warning: "路线服务暂时不可用。" }; const data = await response.json() as { code?: string; routes?: Array<{ geometry?: unknown }> }; const result = data.code === "Ok" && data.routes?.[0]?.geometry ? { geometry: data.routes[0].geometry, warning: null } : { geometry: null, warning: "未能找到该路段的路线。" }; this.save("route_cache", key, result, 7 * 24 * 60 * 60 * 1000); return result; }
  async resolveDay(trip: TripDetail, dayNumber: number): Promise<MapView> { const revision = trip.activeRevision; const day = revision?.plan.days.find((item) => item.dayNumber === dayNumber); if (!revision || !day) throw new Error("当前没有可解析的该日行程。"); const city = trip.requirements.destinations[0]?.city || ""; const markers: MapView["markers"] = [];
    for (let index = 0; index < day.activities.length; index += 1) { const activity = day.activities[index]; const selected = this.store.selectedLocation(trip.id, revision.version, activity.id); const options = selected ? [selected] : await this.geocode([activity.placeName, city].filter(Boolean).join(", ")); const location = selected || (options.length === 1 ? options[0] : null); markers.push({ activityId: activity.id, order: index + 1, placeName: activity.placeName, activity: activity.activity, durationMinutes: activity.durationMinutes, transportMode: activity.transportMode, status: location ? "resolved" : options.length > 1 ? "ambiguous" : "unresolved", location, candidates: options }); }
    const routes: MapView["routes"] = []; for (let index = 1; index < markers.length; index += 1) { const from = markers[index - 1]; const to = markers[index]; const segment = from.location && to.location ? await this.route(from.location, to.location, to.transportMode) : { geometry: null, warning: "地点尚未解析，无法绘制路线。" }; routes.push({ fromActivityId: from.activityId, toActivityId: to.activityId, mode: to.transportMode, geometry: segment.geometry, status: segment.geometry ? "resolved" : "unresolved", warning: segment.warning }); }
    return { dayNumber, dayTitle: day.title, markers, routes };
  }
  selectCandidate(tripId: string, revision: number, activityId: string, value: unknown) { const item = value as Candidate; if (!item || typeof item.providerPlaceId !== "string" || !Number.isFinite(item.latitude) || !Number.isFinite(item.longitude)) throw new Error("地点候选无效。"); this.store.selectLocation(tripId, revision, activityId, item); }
}
