import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import type { Candidate, TravelAgentOutput, TravelRequirements, TripPlan } from "./contracts.js";
import { emptyRequirements, RequirementsSchema, TripPlanSchema } from "./contracts.js";

type SqliteModule = typeof import("node:sqlite");
const sqlite = createRequire(import.meta.url)("node:sqlite") as SqliteModule;
const { DatabaseSync } = sqlite;

export type TripState = "active" | "trashed";
export type TripSummary = { id: string; title: string; state: TripState; updatedAt: string; activeRevision: { id: string; version: number; plan: TripPlan } | null };
export type TripDetail = TripSummary & { requirements: TravelRequirements; requirementsRevision: number; codexThreadId: string | null };
export type ChatMessage = { id: string; role: "user" | "assistant"; content: string; reply: TravelAgentOutput | null; status: "pending" | "completed" | "failed"; turn: { status: "queued" | "starting" | "active" | "completed" | "failed" | "interrupted"; cancelRequested: boolean; errorMessage: string | null; progressMessage?: string } | null; createdAt: string };
export type RevisionSummary = { version: number; createdAt: string; source: string; summary: string };
type DbRow = Record<string, unknown>;
const iso = () => new Date().toISOString();
const json = <T>(value: T) => JSON.stringify(value);
const parse = <T>(value: unknown, fallback: T): T => { try { return typeof value === "string" ? JSON.parse(value) as T : fallback; } catch { return fallback; } };

export class TravelStore {
  private readonly db: InstanceType<typeof DatabaseSync>;
  constructor(filename: string) { this.db = new DatabaseSync(filename); this.db.exec("PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL;"); this.migrate(); }
  close() { this.db.close(); }
  private migrate() {
    const version = this.db.prepare("PRAGMA user_version").get() as { user_version: number };
    if (version.user_version > 1) throw new Error("travel.sqlite3 版本高于当前应用，已停止写入。");
    if (version.user_version === 0) {
      this.db.exec(`
        CREATE TABLE trips (id TEXT PRIMARY KEY, title TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('active','trashed')), codex_thread_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
        CREATE TABLE requirements (trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE, revision INTEGER NOT NULL, content_json TEXT NOT NULL, updated_at TEXT NOT NULL, updated_by TEXT NOT NULL, PRIMARY KEY(trip_id, revision));
        CREATE TABLE itinerary_revisions (trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE, version INTEGER NOT NULL, plan_json TEXT NOT NULL, requirements_revision INTEGER NOT NULL, created_at TEXT NOT NULL, source TEXT NOT NULL, summary TEXT NOT NULL, PRIMARY KEY(trip_id, version));
        CREATE TABLE messages (id TEXT PRIMARY KEY, trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('user','assistant')), content TEXT NOT NULL, reply_json TEXT, status TEXT NOT NULL, turn_status TEXT, cancel_requested INTEGER NOT NULL DEFAULT 0, progress_message TEXT, error_message TEXT, codex_turn_id TEXT, created_at TEXT NOT NULL);
        CREATE TABLE activity_locations (trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE, revision INTEGER NOT NULL, activity_id TEXT NOT NULL, candidate_json TEXT NOT NULL, PRIMARY KEY(trip_id, revision, activity_id));
        CREATE INDEX messages_trip_created ON messages(trip_id, created_at);
        PRAGMA user_version = 1;
      `);
    }
  }
  private activeRevision(tripId: string) { const row = this.db.prepare("SELECT version, plan_json FROM itinerary_revisions WHERE trip_id=? ORDER BY version DESC LIMIT 1").get(tripId) as DbRow | undefined; if (!row) return null; const plan = TripPlanSchema.safeParse(parse(row.plan_json, null)); return plan.success ? { id: `${tripId}:${row.version}`, version: Number(row.version), plan: plan.data } : null; }
  private latestRequirements(tripId: string) { const row = this.db.prepare("SELECT revision, content_json, updated_at, updated_by FROM requirements WHERE trip_id=? ORDER BY revision DESC LIMIT 1").get(tripId) as DbRow | undefined; if (!row) return { revision: 0, content: emptyRequirements(), updatedAt: "", updatedBy: "system" }; const content = RequirementsSchema.safeParse(parse(row.content_json, {})); return { revision: Number(row.revision), content: content.success ? content.data : emptyRequirements(), updatedAt: String(row.updated_at), updatedBy: String(row.updated_by) }; }
  private summary(row: DbRow): TripSummary { const revision = this.activeRevision(String(row.id)); return { id: String(row.id), title: String(row.title), state: String(row.state) as TripState, updatedAt: String(row.updated_at), activeRevision: revision }; }
  listTrips(view: TripState = "active") { return (this.db.prepare("SELECT * FROM trips WHERE state=? ORDER BY updated_at DESC").all(view) as DbRow[]).map((row) => this.summary(row)); }
  createTrip() { const id = randomUUID(); const now = iso(); this.db.prepare("INSERT INTO trips(id,title,state,created_at,updated_at) VALUES(?,?,?,?,?)").run(id, "未命名旅行", "active", now, now); this.db.prepare("INSERT INTO requirements(trip_id,revision,content_json,updated_at,updated_by) VALUES(?,?,?,?,?)").run(id, 1, json(emptyRequirements()), now, "system"); return this.getTrip(id)!; }
  getTrip(id: string): TripDetail | null { const row = this.db.prepare("SELECT * FROM trips WHERE id=?").get(id) as DbRow | undefined; if (!row) return null; const requirements = this.latestRequirements(id); return { ...this.summary(row), requirements: requirements.content, requirementsRevision: requirements.revision, codexThreadId: typeof row.codex_thread_id === "string" ? row.codex_thread_id : null }; }
  requireTrip(id: string) { const trip = this.getTrip(id); if (!trip) throw new Error("找不到这趟旅行。"); return trip; }
  rename(id: string, title: string) { const trimmed = title.trim().slice(0, 200); if (!trimmed) throw new Error("旅行名称不能为空。"); this.db.prepare("UPDATE trips SET title=?, updated_at=? WHERE id=?").run(trimmed, iso(), id); return this.requireTrip(id); }
  duplicate(id: string) { const source = this.requireTrip(id); const next = this.createTrip(); this.rename(next.id, `${source.title} 副本`); const req = this.latestRequirements(id); const now = iso(); this.db.prepare("UPDATE requirements SET content_json=?, updated_at=?, updated_by=? WHERE trip_id=? AND revision=1").run(json(req.content), now, "system", next.id); if (source.activeRevision) this.insertRevision(next.id, source.activeRevision.plan, 1, "duplicate", `复制自 ${source.title}`); return this.requireTrip(next.id); }
  setState(id: string, state: TripState) { this.db.prepare("UPDATE trips SET state=?, updated_at=? WHERE id=?").run(state, iso(), id); return this.requireTrip(id); }
  permanentDelete(id: string) { this.db.prepare("DELETE FROM trips WHERE id=?").run(id); }
  setThread(id: string, threadId: string | null) { this.db.prepare("UPDATE trips SET codex_thread_id=?, updated_at=? WHERE id=?").run(threadId, iso(), id); }
  saveRequirements(id: string, content: unknown, expectedRevision: number, updatedBy: "user" | "agent" | "system" = "user") { const current = this.latestRequirements(id); if (current.revision !== expectedRevision) throw new Error("需求总览已被更新，请重新读取后再保存。"); const parsed = RequirementsSchema.parse(content); const revision = current.revision + 1; const now = iso(); this.db.prepare("INSERT INTO requirements(trip_id,revision,content_json,updated_at,updated_by) VALUES(?,?,?,?,?)").run(id, revision, json(parsed), now, updatedBy); this.db.prepare("UPDATE trips SET updated_at=? WHERE id=?").run(now, id); return { revision, content: parsed, updatedAt: now, updatedBy };
  }
  listMessages(tripId: string): ChatMessage[] { return (this.db.prepare("SELECT * FROM messages WHERE trip_id=? ORDER BY created_at ASC").all(tripId) as DbRow[]).map((row) => ({ id: String(row.id), role: String(row.role) as "user" | "assistant", content: String(row.content), reply: row.reply_json ? parse<TravelAgentOutput | null>(row.reply_json, null) : null, status: String(row.status) as ChatMessage["status"], turn: row.turn_status ? { status: String(row.turn_status) as NonNullable<ChatMessage["turn"]>["status"], cancelRequested: Boolean(row.cancel_requested), errorMessage: row.error_message ? String(row.error_message) : null, ...(row.progress_message ? { progressMessage: String(row.progress_message) } : {}) } : null, createdAt: String(row.created_at) })); }
  createUserMessage(tripId: string, content: string, retryOf?: string | null) { const id = randomUUID(); const now = iso(); this.db.prepare("INSERT INTO messages(id,trip_id,role,content,status,turn_status,progress_message,created_at) VALUES(?,?,?,?,?,?,?,?)").run(id, tripId, "user", content, "pending", "queued", retryOf ? "正在重试请求" : "请求已提交", now); return id; }
  updateTurn(messageId: string, status: NonNullable<ChatMessage["turn"]>["status"], patch: { progress?: string; error?: string | null; cancelRequested?: boolean; codexTurnId?: string } = {}) { const completed = ["completed", "failed", "interrupted"].includes(status); this.db.prepare("UPDATE messages SET status=?,turn_status=?,progress_message=?,error_message=?,cancel_requested=?,codex_turn_id=COALESCE(?,codex_turn_id) WHERE id=?").run(completed && status === "completed" ? "completed" : completed ? "failed" : "pending", status, patch.progress ?? null, patch.error ?? null, patch.cancelRequested ? 1 : 0, patch.codexTurnId ?? null, messageId); }
  private insertRevision(tripId: string, plan: TripPlan, requirementsRevision: number, source: string, summary: string) { const next = Number((this.db.prepare("SELECT COALESCE(MAX(version),0) AS value FROM itinerary_revisions WHERE trip_id=?").get(tripId) as DbRow).value) + 1; const now = iso(); this.db.prepare("INSERT INTO itinerary_revisions(trip_id,version,plan_json,requirements_revision,created_at,source,summary) VALUES(?,?,?,?,?,?,?)").run(tripId, next, json(plan), requirementsRevision, now, source, summary.slice(0, 240)); this.db.prepare("UPDATE trips SET title=?,updated_at=? WHERE id=?").run(plan.tripName.slice(0, 200), now, tripId); return next; }
  applyAgentOutput(tripId: string, userMessageId: string, output: TravelAgentOutput) { this.db.exec("BEGIN IMMEDIATE"); try { const current = this.latestRequirements(tripId); const req = this.saveRequirements(tripId, output.requirements, current.revision, "agent"); let version: number | null = null; if (output.plan) version = this.insertRevision(tripId, output.plan, req.revision, "agent", output.assistantMessage.replace(/\s+/g, " ")); const now = iso(); this.db.prepare("INSERT INTO messages(id,trip_id,role,content,reply_json,status,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(), tripId, "assistant", output.assistantMessage, json(output), "completed", now); this.updateTurn(userMessageId, "completed", { progress: version ? `行程已更新为 v${version}` : "需求已整理" }); this.db.exec("COMMIT"); return { version, requirements: req }; } catch (error) { this.db.exec("ROLLBACK"); throw error; } }
  listRevisions(tripId: string): RevisionSummary[] { return (this.db.prepare("SELECT version,created_at,source,summary FROM itinerary_revisions WHERE trip_id=? ORDER BY version DESC").all(tripId) as DbRow[]).map((row) => ({ version: Number(row.version), createdAt: String(row.created_at), source: String(row.source), summary: String(row.summary) })); }
  getRevision(tripId: string, version: number) { const row = this.db.prepare("SELECT * FROM itinerary_revisions WHERE trip_id=? AND version=?").get(tripId, version) as DbRow | undefined; if (!row) return null; const plan = TripPlanSchema.parse(parse(row.plan_json, {})); const requirements = this.db.prepare("SELECT content_json FROM requirements WHERE trip_id=? AND revision=?").get(tripId, Number(row.requirements_revision)) as DbRow | undefined; return { version: Number(row.version), createdAt: String(row.created_at), source: String(row.source), summary: String(row.summary), plan, requirements: RequirementsSchema.parse(parse(requirements?.content_json, {})) }; }
  restoreRevision(tripId: string, version: number) { const old = this.getRevision(tripId, version); if (!old) throw new Error("找不到该行程版本。"); this.db.exec("BEGIN IMMEDIATE"); try { const current = this.latestRequirements(tripId); const req = this.saveRequirements(tripId, old.requirements, current.revision, "system"); const next = this.insertRevision(tripId, old.plan, req.revision, "restore", `从 v${version} 恢复`); this.db.exec("COMMIT"); return { version: next, trip: this.requireTrip(tripId) }; } catch (error) { this.db.exec("ROLLBACK"); throw error; } }
  selectedLocation(tripId: string, revision: number, activityId: string): Candidate | null { const row = this.db.prepare("SELECT candidate_json FROM activity_locations WHERE trip_id=? AND revision=? AND activity_id=?").get(tripId, revision, activityId) as DbRow | undefined; return row ? parse<Candidate | null>(row.candidate_json, null) : null; }
  selectLocation(tripId: string, revision: number, activityId: string, candidate: Candidate) { this.db.prepare("INSERT INTO activity_locations(trip_id,revision,activity_id,candidate_json) VALUES(?,?,?,?) ON CONFLICT(trip_id,revision,activity_id) DO UPDATE SET candidate_json=excluded.candidate_json").run(tripId, revision, activityId, json(candidate)); }
}
