import { ChevronDown, ChevronUp, CircleStop, LoaderCircle, RotateCcw, Send, Sparkles } from "lucide-react";
import { type FormEvent, useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
export type Chat = { id: string; role: "user" | "assistant"; content: string; reply: { replyType: string; assumptions?: string[] } | null; status: "pending" | "completed" | "failed"; turn: { status: "deferred" | "queued" | "starting" | "active" | "completed" | "failed" | "interrupted"; cancelRequested: boolean; errorMessage: string | null; progressMessage?: string } | null };
const prompts = ["直接做方案", "把节奏放慢一些", "优先照顾老人和孩子", "整理当前待定项"];
export function AssistantDrawer({ title, chat, busy, error, onSend, onStop, onRetry }: { title: string | null; chat: Chat[]; busy: boolean; error: string; onSend: (text: string, retry?: string | null) => Promise<void>; onStop: (id: string) => Promise<void>; onRetry: (id: string, text: string) => Promise<void> }) {
  const [expanded, setExpanded] = useState(false); const [input, setInput] = useState(""); const end = useRef<HTMLDivElement>(null);
  useEffect(() => { if (expanded) end.current?.scrollIntoView({ block: "end" }); }, [expanded, chat, busy]);
  async function submit(event: FormEvent) { event.preventDefault(); const value = input.trim(); if (!value || !title || busy) return; setInput(""); await onSend(value); }
  if (!expanded) return <button className="assistant-bar" onClick={() => setExpanded(true)} aria-label="展开 AI 对话"><Sparkles size={17}/><span className="assistant-context-label">{title || "AI 旅行顾问"}</span><span className="assistant-bar-prompt">问 AI：告诉我想去哪里，或继续调整需求…</span>{busy && <LoaderCircle className="spin" size={16}/>}<span>展开</span><ChevronUp size={18}/></button>;
  return <section className="assistant-drawer" aria-label="AI 旅行顾问"><header className="assistant-head"><strong>{title || "AI 旅行顾问"}</strong><div><span className="assistant-thread-note">单一旅行线程</span><button className="icon-button" onClick={() => setExpanded(false)} aria-label="收起 AI 对话"><ChevronDown size={19}/></button></div></header><div className="assistant-context"><Sparkles size={14}/><span>AI 会结合需求总览决定追问、假设或直接更新行程。</span></div><div className="assistant-body">{!title && <div className="assistant-opening">先新建一趟旅行。之后可以直接告诉我目的地。</div>}{chat.map((row) => <article key={row.id} className={`message ${row.role}`}>{row.role === "assistant" ? <ReactMarkdown remarkPlugins={[remarkGfm]}>{row.content}</ReactMarkdown> : <p>{row.content}</p>}{row.role === "user" && row.turn && <div className={`turn-status ${row.turn.status}`}><small>{row.turn.cancelRequested ? "正在停止…" : ["failed","interrupted"].includes(row.turn.status) ? row.turn.errorMessage || row.turn.progressMessage || "本轮没有完成。" : row.turn.progressMessage || row.turn.status}</small>{["queued","starting","active"].includes(row.turn.status) && <button onClick={() => void onStop(row.id)}>停止</button>}{["failed","interrupted"].includes(row.turn.status) && <button onClick={() => void onRetry(row.id, row.content)}><RotateCcw size={13}/>重试</button>}</div>}</article>)}{error && <p className="inline-error">{error}</p>}<div ref={end}/></div><div className="assistant-compose-zone">{!input && title && <div className="assistant-quick-prompts">{prompts.map((prompt) => <button key={prompt} onClick={() => setInput(prompt)}>{prompt}</button>)}</div>}<form className="assistant-composer" onSubmit={submit}><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} rows={2} maxLength={4000} disabled={!title || busy} placeholder={title ? "输入需求或修改要求…" : "请先新建旅行"}/>{busy ? <button type="button" className="icon-button danger" onClick={() => { const active = [...chat].reverse().find((item) => item.turn && ["queued","starting","active"].includes(item.turn.status)); if (active) void onStop(active.id); }}><CircleStop size={20}/></button> : <button className="icon-button primary" disabled={!title || !input.trim()}><Send size={18}/></button>}</form></div></section>;
}
