import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, LoaderCircle, RotateCcw } from "lucide-react";
import { api } from "./api";
import type { Candidate, MapEntity, MapPatch, MapRoute, MapSnapshot, TripPlan } from "./types";

type JobUpdate = { tripId: string; itineraryVersion: number; mapVersion: number; status: MapSnapshot["status"]; summary: string } | null;
const pointFeature = (item: MapEntity) => ({ type: "Feature" as const, id: item.id, geometry: { type: "Point" as const, coordinates: [item.location!.longitude, item.location!.latitude] }, properties: { id: item.id, name: item.name, kind: item.kind, importance: item.importance, dayNumber: item.dayNumber, time: [item.startTime, item.endTime].filter(Boolean).join("–"), detail: item.detail, duration: item.durationMinutes, transportMode: item.transportMode, costNote: item.costNote, notes: item.notes, city: item.city, sourceUrl: item.location!.sourceUrl, sourceType: item.location!.sourceType, evidenceUrl: item.location!.evidenceUrl || "", confidence: item.location!.confidence, decisionNote: item.location!.decisionNote || "", approximateLodgingArea: item.approximateLodgingArea } });
const routeFeature = (item: MapRoute) => ({ type: "Feature" as const, id: item.id, geometry: item.geometry!, properties: { id: item.id, mode: item.mode, dayNumber: item.dayNumber } });
const mapById = <T extends { id: string }>(values: T[]) => new Map(values.map((item) => [item.id, item]));

export function MapPanel({ tripId, plan, revision, patch, job }: { tripId: string | null; plan: TripPlan | null; revision: number | null; patch: MapPatch | null; job: JobUpdate }) {
  const element = useRef<HTMLDivElement>(null); const mapRef = useRef<any>(null); const popupRef = useRef<any>(null); const pinnedRef = useRef(false); const previousPoints = useRef(new Map<string, string>()); const previousRoutes = useRef(new Map<string, string>()); const fitKey = useRef(""); const [ready, setReady] = useState(false); const [scope, setScope] = useState<"all" | "day">("all"); const [day, setDay] = useState(1); const [snapshot, setSnapshot] = useState<MapSnapshot | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const days = plan?.days || [];
  const load = async (selectedScope = scope, selectedDay = day) => { if (!tripId || !revision) { setSnapshot(null); return; } setLoading(true); try { const query = selectedScope === "day" ? `scope=day&dayNumber=${selectedDay}` : "scope=all"; const data = await api<{ map: MapSnapshot | null }>(`/api/trips/${tripId}/map?${query}`); setSnapshot(data.map); setNotice(""); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "地图加载失败。"); } finally { setLoading(false); } };
  useEffect(() => { setScope("all"); setDay(days[0]?.dayNumber || 1); setSnapshot(null); previousPoints.current.clear(); previousRoutes.current.clear(); fitKey.current = ""; void load("all", days[0]?.dayNumber || 1); }, [tripId, revision]);
  useEffect(() => { if (!patch || patch.tripId !== tripId || patch.itineraryVersion !== revision) return; setSnapshot((current) => { if (!current || current.mapVersion !== patch.mapVersion) { void load(); return current; } const accepts = (item: { dayNumber: number }) => current.scope === "all" || item.dayNumber === current.dayNumber; const entities = mapById(current.entities); for (const id of patch.entities.remove) entities.delete(id); for (const item of patch.entities.upsert) { if (accepts(item)) entities.set(item.id, item); else entities.delete(item.id); } const routes = mapById(current.routes); for (const id of patch.routes.remove) routes.delete(id); for (const item of patch.routes.upsert) { if (accepts(item)) routes.set(item.id, item); else routes.delete(item.id); } return { ...current, entities: [...entities.values()], routes: [...routes.values()] }; }); }, [patch]);
  useEffect(() => { if (!job || job.tripId !== tripId || job.itineraryVersion !== revision) return; setSnapshot((current) => current ? { ...current, status: job.status, summary: job.summary } : current); }, [job]);
  useEffect(() => { let map: any; let cancelled = false; void import("maplibre-gl").then((lib) => { if (!element.current || cancelled) return; map = new lib.Map({ container: element.current, style: { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm" }] }, center: [0, 20], zoom: 1.1 }); map.addControl(new lib.NavigationControl({ showCompass: false }), "top-right"); map.on("load", () => { map.addSource("travel-routes", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "travel-routes", type: "line", source: "travel-routes", paint: { "line-color": ["match", ["get", "mode"], "drive", "#dc2626", "walk", "#2563eb", "bike", "#16a34a", "#64748b"], "line-width": ["match", ["get", "mode"], "drive", 5, 3], "line-opacity": .82 } }); map.addSource("travel-places", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "travel-places", type: "circle", source: "travel-places", paint: { "circle-radius": ["match", ["get", "importance"], "primary", 8, "secondary", 6, 5], "circle-color": ["match", ["get", "kind"], "city", "#1b4f78", "lodging", "#7c3aed", "meal", "#d97706", "#e11d48"], "circle-stroke-width": 2, "circle-stroke-color": "#ffffff" } });
        const showPopup = (event: any, pinned: boolean) => { const feature = event.features?.[0]; if (!feature) return; const properties = feature.properties || {}; const content = document.createElement("div"); content.className = "map-popup-content"; const title = document.createElement("strong"); title.textContent = properties.name || "地点"; const meta = document.createElement("small"); meta.textContent = [`Day ${properties.dayNumber}`, properties.time, properties.city].filter(Boolean).join(" · "); const detail = document.createElement("p"); detail.textContent = properties.detail || ""; const extra = document.createElement("small"); extra.textContent = [`停留 ${properties.duration || 0} 分钟`, properties.transportMode, properties.costNote, properties.notes].filter(Boolean).join(" · "); const source = document.createElement("small"); const sourceNames: Record<string, string> = { nominatim: "OpenStreetMap Nominatim", ai_web: "AI 网页核验", ai_knowledge: "AI 知识估算", manual: "用户手工确认" }; source.textContent = [`坐标来源：${sourceNames[properties.sourceType] || "未知"}`, properties.confidence ? `置信度：${properties.confidence}` : "", properties.approximateLodgingArea ? "未指定酒店，仅代表计划住宿区域" : "", properties.decisionNote].filter(Boolean).join(" · "); const link = document.createElement("a"); link.textContent = "在 OpenStreetMap 查看"; link.href = properties.sourceUrl || "https://www.openstreetmap.org"; link.target = "_blank"; link.rel = "noreferrer"; content.append(title, meta, detail, extra, source, link); if (properties.evidenceUrl) { const evidence = document.createElement("a"); evidence.textContent = "查看坐标依据"; evidence.href = properties.evidenceUrl; evidence.target = "_blank"; evidence.rel = "noreferrer"; content.append(evidence); } popupRef.current?.remove(); popupRef.current = new lib.Popup({ offset: 14, closeButton: pinned, closeOnClick: false }).setLngLat(event.lngLat).setDOMContent(content).addTo(map); pinnedRef.current = pinned; };
        map.on("mouseenter", "travel-places", (event: any) => { map.getCanvas().style.cursor = "pointer"; if (!pinnedRef.current) showPopup(event, false); }); map.on("mouseleave", "travel-places", () => { map.getCanvas().style.cursor = ""; if (!pinnedRef.current) popupRef.current?.remove(); }); map.on("click", "travel-places", (event: any) => showPopup(event, true)); map.on("click", (event: any) => { if (!map.queryRenderedFeatures(event.point, { layers: ["travel-places"] }).length) { pinnedRef.current = false; popupRef.current?.remove(); } }); setReady(true); }); const observer = new ResizeObserver(() => map.resize()); observer.observe(element.current); mapRef.current = map; }).catch(() => setNotice("地图渲染组件加载失败。")); return () => { cancelled = true; popupRef.current?.remove(); map?.remove(); mapRef.current = null; setReady(false); }; }, []);
  useEffect(() => { const map = mapRef.current; if (!ready || !map || !snapshot) return; const pointSource = map.getSource("travel-places"); const routeSource = map.getSource("travel-routes"); if (!pointSource || !routeSource) return; const pointFeatures = snapshot.entities.filter((item) => item.location).map(pointFeature); const routeFeatures = snapshot.routes.filter((item) => item.status === "resolved" && item.geometry).map(routeFeature); const sync = (source: any, previous: React.MutableRefObject<Map<string, string>>, features: any[]) => { const next = new Map(features.map((feature) => [String(feature.id), JSON.stringify(feature)])); const remove = [...previous.current.keys()].filter((id) => !next.has(id)); const add = features.filter((feature) => !previous.current.has(String(feature.id))); const update = features.filter((feature) => previous.current.has(String(feature.id)) && previous.current.get(String(feature.id)) !== next.get(String(feature.id))).map((feature) => ({ id: feature.id, newGeometry: feature.geometry, removeAllProperties: true, addOrUpdateProperties: feature.properties })); if (remove.length || add.length || update.length) void source.updateData({ remove, add, update }); previous.current = next; }; sync(pointSource, previousPoints, pointFeatures); sync(routeSource, previousRoutes, routeFeatures);
    const key = `${tripId}:${revision}:${scope}:${scope === "day" ? day : "all"}`; if (pointFeatures.length && fitKey.current !== key) { void import("maplibre-gl").then((lib) => { const bounds = new lib.LngLatBounds(); for (const feature of pointFeatures) bounds.extend(feature.geometry.coordinates as [number, number]); if (!bounds.isEmpty()) map.fitBounds(bounds, { padding: 54, maxZoom: 13, duration: 500 }); fitKey.current = key; }); }
  }, [ready, snapshot, tripId, revision, scope, day]);
  const unresolved = useMemo(() => snapshot?.entities.filter((item) => item.status === "ambiguous") || [], [snapshot]); const running = snapshot && ["queued", "analyzing", "resolving"].includes(snapshot.status);
  const select = async (entityId: string, candidate: Candidate) => { if (!tripId) return; try { await api(`/api/trips/${tripId}/map/locations/${encodeURIComponent(entityId)}/select`, { method: "POST", body: JSON.stringify({ candidate }) }); await load(); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "地点选择失败。"); } };
  const retry = async () => { if (!tripId) return; setLoading(true); try { await api(`/api/trips/${tripId}/map/retry`, { method: "POST", body: "{}" }); await load(); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "地图重试失败。"); } finally { setLoading(false); } };
  return <section className="map-panel"><div className="map-heading"><div><h2>地图</h2><p>{scope === "all" ? "全程总览" : `Day ${day} · ${days.find((item) => item.dayNumber === day)?.title || ""}`}</p></div>{plan && <div className="map-actions"><select value={scope === "all" ? "all" : String(day)} onChange={(event) => { const value = event.target.value; const nextScope = value === "all" ? "all" : "day"; const nextDay = value === "all" ? day : Number(value); setScope(nextScope); setDay(nextDay); fitKey.current = ""; void load(nextScope, nextDay); }}><option value="all">全程总览</option>{days.map((item) => <option key={item.dayNumber} value={item.dayNumber}>Day {item.dayNumber}</option>)}</select>{snapshot && ["partial", "failed"].includes(snapshot.status) && <button disabled={loading} onClick={() => void retry()}><RotateCcw size={12}/>{loading ? "重试中" : "重试未完成项"}</button>}</div>}</div><div ref={element} className="map-canvas"/>{unresolved.length > 0 && <div className="map-candidates">{unresolved.map((item) => <div key={item.id}><b>{item.name}：请选择地点</b>{item.candidates.map((candidate) => <button key={candidate.providerPlaceId} onClick={() => void select(item.id, candidate)}>{candidate.displayName}</button>)}</div>)}</div>}<p className={`map-notice ${snapshot?.status || "idle"}`}>{running ? <LoaderCircle className="spin" size={13}/> : snapshot?.status === "partial" || snapshot?.status === "failed" ? <AlertTriangle size={13}/> : null}<span>{notice || snapshot?.summary || (plan ? "地图 Agent 将在后台自动标注全程地点和路线。" : "生成行程后会自动建立地图。")}</span></p><a className="map-credit" href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">© OpenStreetMap contributors · 报告地图问题</a></section>;
}
