import { useEffect, useMemo, useRef, useState } from "react";
import type { TripPlan } from "./types";
import { api } from "./api";
type Candidate = { providerPlaceId: string; displayName: string; latitude: number; longitude: number; category: string | null; sourceUrl: string };
type MapView = { dayNumber: number; dayTitle: string; markers: Array<{ activityId: string; order: number; placeName: string; activity: string; durationMinutes: number; transportMode: string; status: string; location: Candidate | null; candidates: Candidate[] }>; routes: Array<{ fromActivityId: string; toActivityId: string; mode: string; geometry: any; status: string; warning: string | null }> };
export function MapPanel({ tripId, plan }: { tripId: string | null; plan: TripPlan | null }) {
  const element = useRef<HTMLDivElement>(null); const mapRef = useRef<any>(null); const markersRef = useRef<any[]>([]); const [day, setDay] = useState(1); const [view, setView] = useState<MapView | null>(null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const days = plan?.days || [];
  useEffect(() => { setDay(days[0]?.dayNumber || 1); setView(null); setNotice(""); }, [tripId, plan, days.length]);
  useEffect(() => { let map: any; let cancelled = false; void import("maplibre-gl").then((lib) => { if (!element.current || cancelled) return; map = new lib.Map({ container: element.current, style: { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm" }] }, center: [0, 20], zoom: 1.1 }); map.addControl(new lib.NavigationControl({ showCompass: false }), "top-right"); map.on("load", () => { map.addSource("routes", { type: "geojson", data: { type: "FeatureCollection", features: [] } }); map.addLayer({ id: "routes", type: "line", source: "routes", paint: { "line-color": ["match", ["get", "mode"], "walk", "#2563eb", "bike", "#16a34a", "drive", "#dc2626", "#64748b"], "line-width": 4, "line-opacity": .8 } }); }); const observer = new ResizeObserver(() => map.resize()); observer.observe(element.current); mapRef.current = map; }).catch(() => setNotice("地图渲染组件加载失败。")); return () => { cancelled = true; map?.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map || !view) return; void import("maplibre-gl").then((lib) => { markersRef.current.forEach((marker) => marker.remove()); markersRef.current = []; const bounds = new lib.LngLatBounds(); for (const item of view.markers) { if (!item.location) continue; const popupContent = document.createElement("div"); const title = document.createElement("strong"); title.textContent = `${item.order}. ${item.placeName}`; popupContent.append(title, document.createElement("br"), document.createTextNode(item.activity)); const popup = new lib.Popup({ offset: 20 }).setDOMContent(popupContent); markersRef.current.push(new lib.Marker({ color: item.transportMode === "drive" ? "#dc2626" : "#4f46e5" }).setLngLat([item.location.longitude, item.location.latitude]).setPopup(popup).addTo(map)); bounds.extend([item.location.longitude, item.location.latitude]); } const source = map.getSource("routes"); source?.setData({ type: "FeatureCollection", features: view.routes.filter((route) => route.status === "resolved" && route.geometry).map((route) => ({ type: "Feature", properties: { mode: route.mode }, geometry: route.geometry })) }); if (!bounds.isEmpty()) map.fitBounds(bounds, { padding: 54, maxZoom: 13, duration: 500 }); }); }, [view]);
  const unresolved = useMemo(() => view?.markers.filter((item) => item.status === "ambiguous") || [], [view]);
  async function resolve() { if (!tripId) return; setLoading(true); setNotice(""); try { const data = await api<{ map: MapView }>(`/api/trips/${tripId}/map`, { method: "POST", body: JSON.stringify({ dayNumber: day }) }); setView(data.map); if (data.map.markers.some((item) => item.status === "unresolved")) setNotice("部分地点尚未解析；行程内容未受影响。"); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "地图解析失败。"); } finally { setLoading(false); } }
  async function select(activityId: string, value: Candidate) { if (!tripId) return; try { await api(`/api/trips/${tripId}/map/locations/${activityId}/select`, { method: "POST", body: JSON.stringify({ candidate: value }) }); await resolve(); } catch (cause) { setNotice(cause instanceof Error ? cause.message : "地点选择失败。"); } }
  return <section className="map-panel"><div className="map-heading"><div><h2>地图</h2><p>{plan ? `Day ${day} · ${days.find((item) => item.dayNumber === day)?.title || ""}` : "等待行程提案"}</p></div>{plan && <div className="map-actions"><select value={day} onChange={(event) => { setDay(Number(event.target.value)); setView(null); }}>{days.map((item) => <option key={item.dayNumber} value={item.dayNumber}>Day {item.dayNumber}</option>)}</select><button disabled={!tripId || loading} onClick={() => void resolve()}>{loading ? "解析中…" : "解析此日地图"}</button></div>}</div><div ref={element} className="map-canvas"/>{unresolved.length > 0 && <div className="map-candidates">{unresolved.map((item) => <div key={item.activityId}><b>{item.placeName}：请选择地点</b>{item.candidates.map((option) => <button key={option.providerPlaceId} onClick={() => void select(item.activityId, option)}>{option.displayName}</button>)}</div>)}</div>}<p className="map-notice">{notice || (plan ? "仅在点击“解析此日地图”后访问公开地点与路线服务；公共交通仅作未实时核验建议。" : "生成行程后，可按天解析地点和路线。")}</p><a className="map-credit" href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">报告地图问题</a></section>;
}
