import { FilePenLine, LoaderCircle, PanelRightClose, RotateCcw, Save } from "lucide-react";
import { forwardRef, useEffect, useImperativeHandle, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api } from "./api";
type Document = { content: string; revision: number; updatedAt: string; updatedBy: string };
export type RequirementsDrawerHandle = { savePendingDraft: () => Promise<boolean> };
export const RequirementsDrawer = forwardRef<RequirementsDrawerHandle, { tripId: string | null; refreshKey: number; onClose: () => void }>(function RequirementsDrawer({ tripId, refreshKey, onClose }, ref) {
  const [document, setDocument] = useState<Document | null>(null); const [draft, setDraft] = useState(""); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => { if (!tripId) { setDocument(null); setDraft(""); return; } setLoading(true); try { const result = await api<{ document: Document }>(`/api/trips/${tripId}/requirements`); setDocument(result.document); setDraft(result.document.content); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法读取需求总览。"); } finally { setLoading(false); } };
  useEffect(() => { if (!(editing && document && draft !== document.content)) void load(); }, [tripId, refreshKey]);
  const save = async () => { if (!tripId || !document || draft === document.content) return true; setSaving(true); try { const result = await api<{ document: Document }>(`/api/trips/${tripId}/requirements`, { method: "PUT", body: JSON.stringify({ content: draft, expectedRevision: document.revision }) }); setDocument(result.document); setDraft(result.document.content); setEditing(false); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "无法保存需求总览。"); return false; } finally { setSaving(false); } };
  useImperativeHandle(ref, () => ({ savePendingDraft: save }), [tripId, document, draft]); const dirty = Boolean(document && draft !== document.content);
  return <aside className="requirements-drawer"><header className="requirements-drawer-head"><div><strong>需求总览</strong><small>{tripId ? "与 AI 共同维护的工作稿" : "新建旅行后开始整理"}</small></div><div className="requirements-actions">{editing && <button className="icon-button" onClick={() => { setDraft(document?.content || ""); setEditing(false); }}><RotateCcw size={16}/></button>}{editing ? <button className="icon-button primary" disabled={!dirty || saving} onClick={() => void save()}>{saving ? <LoaderCircle className="spin" size={16}/> : <Save size={16}/>}</button> : <button className="icon-button" disabled={!tripId || loading} onClick={() => setEditing(true)}><FilePenLine size={16}/></button>}<button className="icon-button" onClick={onClose}><PanelRightClose size={19}/></button></div></header><div className="requirements-status">{loading ? <><LoaderCircle className="spin" size={13}/>正在同步</> : document ? <><span className={`document-source ${document.updatedBy}`}>{document.updatedBy === "user" ? "已由你保存" : "AI 已同步"}</span><time>{new Date(document.updatedAt).toLocaleString("zh-CN")}</time></> : "等待选择旅行"}</div>{error && <p className="inline-error">{error}</p>}<div className="requirements-document">{!tripId ? <p className="requirements-empty">这里会沉淀目的地、待定项和 AI 的规划假设。</p> : editing ? <textarea value={draft} onChange={(event) => setDraft(event.target.value)} spellCheck={false}/> : <div className="requirements-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{document?.content || "正在读取…"}</ReactMarkdown></div>}</div>{editing && <footer className="requirements-footer"><span>{dirty ? "有未保存修改" : "没有未保存修改"}</span><button className="button primary small" disabled={!dirty || saving} onClick={() => void save()}>{saving ? "保存中…" : "保存"}</button></footer>}</aside>;
});
